default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: riza

development:
  <<: *default
  database: zeemitest_dev
test:
  <<: *default
  database: zeemitest_test
production:
  <<: *default
  database: zeemitest
  username: riza
